# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trillian_admin_api.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import trillian_pb2 as trillian__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18trillian_admin_api.proto\x12\x08trillian\x1a\x0etrillian.proto\x1a google/protobuf/field_mask.proto\"(\n\x10ListTreesRequest\x12\x14\n\x0cshow_deleted\x18\x01 \x01(\x08\"1\n\x11ListTreesResponse\x12\x1c\n\x04tree\x18\x01 \x03(\x0b\x32\x0e.trillian.Tree\"!\n\x0eGetTreeRequest\x12\x0f\n\x07tree_id\x18\x01 \x01(\x03\"A\n\x11\x43reateTreeRequest\x12\x1c\n\x04tree\x18\x01 \x01(\x0b\x32\x0e.trillian.TreeJ\x04\x08\x02\x10\x03R\x08key_spec\"b\n\x11UpdateTreeRequest\x12\x1c\n\x04tree\x18\x01 \x01(\x0b\x32\x0e.trillian.Tree\x12/\n\x0bupdate_mask\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.FieldMask\"$\n\x11\x44\x65leteTreeRequest\x12\x0f\n\x07tree_id\x18\x01 \x01(\x03\"&\n\x13UndeleteTreeRequest\x12\x0f\n\x07tree_id\x18\x01 \x01(\x03\x32\x86\x03\n\rTrillianAdmin\x12\x46\n\tListTrees\x12\x1a.trillian.ListTreesRequest\x1a\x1b.trillian.ListTreesResponse\"\x00\x12\x35\n\x07GetTree\x12\x18.trillian.GetTreeRequest\x1a\x0e.trillian.Tree\"\x00\x12;\n\nCreateTree\x12\x1b.trillian.CreateTreeRequest\x1a\x0e.trillian.Tree\"\x00\x12;\n\nUpdateTree\x12\x1b.trillian.UpdateTreeRequest\x1a\x0e.trillian.Tree\"\x00\x12;\n\nDeleteTree\x12\x1b.trillian.DeleteTreeRequest\x1a\x0e.trillian.Tree\"\x00\x12?\n\x0cUndeleteTree\x12\x1d.trillian.UndeleteTreeRequest\x1a\x0e.trillian.Tree\"\x00\x42P\n\x19\x63om.google.trillian.protoB\x15TrillianAdminApiProtoP\x01Z\x1agithub.com/google/trillianb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trillian_admin_api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.google.trillian.protoB\025TrillianAdminApiProtoP\001Z\032github.com/google/trillian'
  _globals['_LISTTREESREQUEST']._serialized_start=88
  _globals['_LISTTREESREQUEST']._serialized_end=128
  _globals['_LISTTREESRESPONSE']._serialized_start=130
  _globals['_LISTTREESRESPONSE']._serialized_end=179
  _globals['_GETTREEREQUEST']._serialized_start=181
  _globals['_GETTREEREQUEST']._serialized_end=214
  _globals['_CREATETREEREQUEST']._serialized_start=216
  _globals['_CREATETREEREQUEST']._serialized_end=281
  _globals['_UPDATETREEREQUEST']._serialized_start=283
  _globals['_UPDATETREEREQUEST']._serialized_end=381
  _globals['_DELETETREEREQUEST']._serialized_start=383
  _globals['_DELETETREEREQUEST']._serialized_end=419
  _globals['_UNDELETETREEREQUEST']._serialized_start=421
  _globals['_UNDELETETREEREQUEST']._serialized_end=459
  _globals['_TRILLIANADMIN']._serialized_start=462
  _globals['_TRILLIANADMIN']._serialized_end=852
# @@protoc_insertion_point(module_scope)
